STRIPE_PUBLIC_KEY : STRIPE PUBLIC KEY
STRIPE_SECRET_KEY : sk_test_51LuZLeKHclTRBfJZSeoAM6zLnf38sOt5g0NiYOOcpYKNQJ2KyQ7k1yOMgGxPJh6rulthuUQ7HaAvWnMNxnqWom1L00FcJdciuQ
BASE_URL: http://localhost:8081/
spring:
  application:
    name: LMS.CheckoutService
server:
  port: 8092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  
  